apiVersion: apps/v1
kind: Deployment
metadata:
  name: news-portal-deployment
spec:
  replicas: 3
  template:
    metadata:
      name: news-portal
      labels:
        app: news-portal
    spec:
      containers:
        - name: news-portal-container
          image: aluracursos/portal-noticias:1
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: news-portal-configmap
  selector:
    matchLabels:
      app: news-portal
